### ISSUE TITLE
Error with the hf_arparser.py file 

### ISSUE THREAD

**Issue by xanhho** [wyu97/Easy-use-BART#3]
Hi, thank you for your code, I try to run your code and I got an error about the hf_argparser.py file.
I try to search around but I don't understand why. (I guess it is maybe because the version that I am using is different with you?)
I'm using:
- Python 3.8.10 (this is different)
- transformers==3.3.1
- torch==1.7.0

If you have any clues about the error, please let me know.
Thank you very much for your support.

Here are the details about the error.
```Traceback (most recent call last):
  File "finetune.py", line 302, in <module>
    main()
  File "finetune.py", line 103, in main
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, Seq2SeqTrainingArguments))
  File "/home/xanh_2/vir_bart/lib/python3.8/site-packages/transformers/hf_argparser.py", line 40, in __init__
    self._add_dataclass_arguments(dtype)
  File "/home/xanh_2/vir_bart/lib/python3.8/site-packages/transformers/hf_argparser.py", line 80, in _add_dataclass_arguments
    elif hasattr(field.type, "__origin__") and issubclass(field.type.__origin__, List):
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by wyu97** [comment]
Hi

Just tried python 3.6 and used the same transformers/torch package but did not get this issue. 

Would this help? https://github.com/huggingface/transformers/issues/6428

**Comment by xanhho** [comment]
> Would this help? https://github.com/huggingface/transformers/issues/6428

=> Thank you for your suggestion, I have read about this but it is not similar to my case (I think).

I try to install the same environment as you described but I get another error, do you have any ideas?

My environment:
- Python 3.6.13
- transformers 3.3.1
- torch 1.7.0

Here is the details about the error:
```Traceback (most recent call last):
  File "/home/xanh_2/Easy-use-BART/seq2seq_trainer.py", line 65, in <module>
    from transformers.utils import label_smoothed_nll_loss
ImportError: cannot import name 'label_smoothed_nll_loss'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "finetune.py", line 8, in <module>
    from seq2seq_trainer import Seq2SeqTrainer
  File "/home/xanh_2/Easy-use-BART/seq2seq_trainer.py", line 67, in <module>
    from utils import label_smoothed_nll_loss
  File "/home/xanh_2/Easy-use-BART/utils.py", line 17, in <module>
    from rouge_score import rouge_scorer, scoring
  File "/home/xanh_2/anaconda3/envs/bart/lib/python3.6/site-packages/rouge_score/rouge_scorer.py", line 49, in <module>
    class RougeScorer(scoring.BaseScorer):
  File "/home/xanh_2/anaconda3/envs/bart/lib/python3.6/site-packages/rouge_score/rouge_scorer.py", line 87, in RougeScorer
    def score_multi(self, targets: list[str], prediction: str):
TypeError: 'type' object is not subscriptable 

Thank you for your support.
